# .github/workflows/keep-alive.yml
name: Trigger Probe of Deployed App on a CRON Schedule
on:
  schedule:
    # Runs “At minute 0 past every 10th hour.” (see https://crontab.guru)... ie: 10PM everyday
    - cron: '0 */10 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment Environment'
        required: false
        default: 'Production'

jobs:
  probe_deployed_app:
    runs-on: ubuntu-latest
    name: A job to probe deployed app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Probe Deployed App Action Step
        uses: ./probe-action # Uses an action in the probe-action directory
        id: probe
  notify:
    needs: [probe_deployed_app]
    if: failure()
    runs-on: ubuntu-latest
    name: Notify Discord
    steps:
      - uses: Jasiri-w/jobs-discord-notification-action@v2.0.1
        with:
          discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          needs_json: ${{ toJSON(needs) }}
          wake_up_log: ${{ needs.probe_deployed_app.outputs.wake_up_log }}
